name: DereeIntroBigData
channels:
  - defaults
dependencies:
  - asttokens=3.0.0=py312haa95532_0
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.12.2=haa95532_0
  - colorama=0.4.6=py312haa95532_0
  - comm=0.2.3=py312haa95532_0
  - debugpy=1.8.16=py312h885b0b7_1
  - decorator=5.2.1=py312haa95532_0
  - executing=2.2.1=py312haa95532_0
  - expat=2.7.3=h885b0b7_4
  - ipykernel=6.31.0=py312h4442805_0
  - ipython=9.7.0=py312haa95532_0
  - ipython_pygments_lexers=1.1.1=py312haa95532_0
  - jedi=0.19.2=py312haa95532_0
  - jupyter_client=8.6.3=py312haa95532_1
  - jupyter_core=5.9.1=py312haa95532_0
  - libexpat=2.7.3=h885b0b7_4
  - libffi=3.4.4=hd77b12b_1
  - libsodium=1.0.20=h83e8143_0
  - libzlib=1.3.1=h02ab6af_0
  - matplotlib-inline=0.2.1=py312haa95532_0
  - nest-asyncio=1.6.0=py312haa95532_0
  - openssl=3.0.18=h543e019_0
  - packaging=25.0=py312haa95532_1
  - parso=0.8.5=py312haa95532_0
  - pip=25.3=pyhc872135_0
  - platformdirs=4.5.0=py312haa95532_0
  - prompt-toolkit=3.0.52=py312haa95532_1
  - prompt_toolkit=3.0.52=hd3eb1b0_1
  - psutil=7.0.0=py312h02ab6af_1
  - pure_eval=0.2.3=py312haa95532_0
  - pygments=2.19.2=py312haa95532_0
  - python=3.12.12=h716150d_1
  - python-dateutil=2.9.0post0=py312haa95532_2
  - pywin32=311=py312h885b0b7_0
  - pyzmq=27.1.0=py312h7149c55_1
  - setuptools=80.9.0=py312haa95532_0
  - six=1.17.0=py312haa95532_0
  - sqlite=3.51.0=hda9a48d_0
  - stack_data=0.6.3=py312haa95532_0
  - tk=8.6.15=hf199647_0
  - tornado=6.5.1=py312h827c3e9_0
  - traitlets=5.14.3=py312haa95532_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wcwidth=0.2.13=py312haa95532_0
  - wheel=0.45.1=py312haa95532_0
  - xz=5.6.4=h4754444_1
  - zeromq=4.3.5=h6c54ac7_1
  - zlib=1.3.1=h02ab6af_0
  - pip:
      - contourpy==1.3.3
      - cycler==0.12.1
      - fonttools==4.61.1
      - hypertools==0.8.1
      - ipympl==0.9.8
      - joblib==1.5.2
      - kiwisolver==1.4.9
      - llvmlite==0.46.0
      - matplotlib==3.10.8
      - numba==0.63.1
      - numpy==2.3.5
      - pandas==2.3.3
      - pillow==12.0.0
      - ppca==0.0.4
      - pymysql==1.1.2
      - pynndescent==0.5.13
      - pyparsing==3.2.5
      - pytz==2025.2
      - scikit-learn==1.8.0
      - scipy==1.16.3
      - seaborn==0.13.2
      - tensorly==0.9.0
      - threadpoolctl==3.6.0
      - tqdm==4.67.1
      - tzdata==2025.2
      - umap-learn==0.5.9.post2
      - widgetsnbextension==4.0.15
prefix: C:\Users\kathe\miniconda3\envs\DereeIntroBigData
